[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm --filter @mentalfit/web build",
  "cp -r apps/web/public apps/web/.next/standalone/apps/web/public",
  "cp -r apps/web/.next/static apps/web/.next/standalone/apps/web/.next/static"
]

[start]
cmd = "cd apps/web/.next/standalone/apps/web && HOSTNAME=0.0.0.0 PORT=3000 node server.js"

[variables]
NODE_ENV = "production"
PORT = "3000"
HOSTNAME = "0.0.0.0"
